### ISSUE TITLE
不能添加子目录

### ISSUE THREAD

**Issue by kookob** [zhaopengme/gitnote#1]
正常字符，提示包含特殊字符
![image](https://user-images.githubusercontent.com/3116606/52094071-972df780-25f8-11e9-8f79-af715d7aa484.png)

**Comment by zhaopengme** [comment]
什么系统呢

**Comment by kllkko** [comment]
一样，也是win10 64位系统

**Comment by zhaopengme** [comment]
刚刚修复了,重新发布了.请重新下载 windows 就可以了.
