### ISSUE TITLE
KityMinder思维导图插件建议

### ISSUE THREAD

**Issue by lzliang82** [zhaopengme/gitnote#105]
## Kityminder中没有关系线的功能。
在同级或夸级之间都可能会遇到关系关联的问题，需要使用关系线进行关联。
![image](https://user-images.githubusercontent.com/16849744/52686490-e6751000-2f88-11e9-9c25-b7280515a0c6.png)

**Comment by zhaopengme** [comment]
我先记下了,可能改的时间会比较长.
