### ISSUE TITLE
使用github插件插入图片能否给个详细的操作，插入的图片只能本地查看

### ISSUE THREAD

**Issue by adeewu** [zhaopengme/gitnote#11]
### 已经配置好github的参数，插入的图片还是这样子
![image](https://user-images.githubusercontent.com/5095500/52099527-9607c500-260e-11e9-857b-610c3757ad31.png)

**Comment by zhaopengme** [comment]
https://gitnoteapp.com/zh/extensions/github.html
这里有这个插件的说明

**Comment by adeewu** [comment]
确实按照这个流程配置好的，就是最后一步插入图片没效果

**Comment by SamuleQiu** [comment]
插入图片通过拖拽图片到编辑区域会显示上传到那个图床
![2019-02-08 13 22 34](https://user-images.githubusercontent.com/46648424/52460361-d7ffb080-2ba4-11e9-9254-b57d1b4b7742.gif)
