### ISSUE TITLE
关于语言选择

### ISSUE THREAD

**Issue by mtclaw** [zhaopengme/gitnote#112]
软件默认是英文，每次打开软件都需要重新选择一遍简中。
可以让软件记住我的选项吗？

**Comment by Remawater** [comment]
我的是记住了  但是并没有去特别设置   
你可以在这里设置一下   不知道有没有用
![image](https://user-images.githubusercontent.com/47489378/52792566-9ee4a600-30a6-11e9-934a-f9d2a035867a.png)

**Comment by mtclaw** [comment]
谢谢，问题解决了
