### ISSUE TITLE
没到开始写笔记那一步发现的问题或建议

### ISSUE THREAD

**Issue by c02y** [zhaopengme/gitnote#12]
1. 不能新建笔记，只能“Add a locally existing GIT repository” 或者“Clone a Resository”，如果我只想只用本地笔记功能或者以后再上传到远程怎么办？
2. Clone a Resository里面的x点击没反应
3. 点击“Add a locally existing GIT repository”进去，填写本地目录（空目录）显示“There is already a git repository”，这是什么意思？
4. 点击首页的“Add a locally existing GIT repository” 或者“Clone a Resository”后面的问号会打开浏览器到www.baidu.com，是要我们自己百度？
5. 所以目前我到现在还没有走到成功开始写笔记的那一步

**Comment by zhaopengme** [comment]
引导没有做好,我找时间加上引导说明.
1. 仅仅用作本地的话,还没有加上这个功能.下一次大的更新我来加这个功能.
2. 这个是 bug
3. 和4 同样的问题,前提是需要你自己有一个 git 仓库. remote 那里填写的是https://github.com/zhaopengme/gitnote

**Comment by ferocknew** [comment]
同遇到：
- 点击“Add a locally existing GIT repository”进去，填写本地目录（空目录）显示“There is already a git repository”，这是什么意思？
- 点击首页的“Add a locally existing GIT repository” 或者“Clone a Resository”后面的问号会打开浏览器到www.baidu.com，是要我们自己百度？

导致无法使用

**Comment by zhaopengme** [comment]
![gitnote](https://user-images.githubusercontent.com/1415418/52105930-a5493b80-262b-11e9-8bf3-2f28c3b6d4b8.gif)
看看这个.

**Comment by zhaopengme** [comment]
必须要是 git 仓库. 存在.git 的.

**Comment by c02y** [comment]
这个我知道，如果我只讲GitNote作为本地笔记应用来使用或者现阶段不使用git管理就没办法了，这算是个建议吧

**Comment by ferocknew** [comment]
> 必须要是 git 仓库. 存在.git 的.

那就意味着用户必须先在命令行执行 
```bash
git init
```
按照这个流程，暂时是可以使用了

**Comment by zhaopengme** [comment]
@ferocknew 先到github 创建 git 仓库. gitnote 从 github 来 clone 你的 git 仓库.是这样的一个流程.

**Comment by zhaopengme** [comment]
@c02y 对,你是想纯粹的 git 本地管理吧.这个也还好实现.我加入 todo 吧
