### ISSUE TITLE
有开源计划吗？

### ISSUE THREAD

**Issue by altairwei** [zhaopengme/gitnote#122]
我很喜欢 GitNote 的设计理念，有几点理由：

1. 使用 Git 作为笔记的版本控制系统是个很棒的想法。Git 是文本文件版本控制最棒的工具，没有之一。
2. Electron 跨平台的特性使得代码库变得统一。
3. JavaScript + NodeJS 的生态系统非常强大。从 GitNote 的诸多插件以及文档编辑器中，我看到了很多熟悉的开源项目。强大的生态系统意味着拓展 GitNote 的功能变得非常容易。
4. JavaScript 是易学易用的语言。尽管现代前端的完整技术栈并不简单，但对于用户来说参与 GitNote 插件开发是一个很好的开始。
5. 剪裁和展示网页变得容易。大部分网页含有丰富的样式，用 HTML 储存和展示剪裁页面能够最大程度还原它的本来面目。

**我很看好 GitNote 的前景，如果该项目有计划开源，请务必告知我。**

**Comment by Remawater** [comment]
开发者说有的   等版本稳定之后会开源

**Comment by linshiyouxiangt1** [comment]
有的,这段时间忙完先,

**Comment by zhaopengme** [comment]
有的,这段时间忙完.请关注官网.

**Comment by qmdx** [comment]
> 有的,这段时间忙完.请关注官网.

非常棒 gitnote 还有很多蹩脚之处，目测作者一个人在开发如果能开源大家一起完善相信它会变得更加棒👍

**Comment by godvmxi** [comment]
Hi Zhaopeng:
   很久没有看到你更新了，并且最新和github的错误越来越多了，最近一直再给朋友安利你的软件，但是在写教程的过程中出了很多的问题。
   从我很久前给你的提的issue来看，您似乎已经经理不太够用，能否建议你将代码开源？便于我们进行后续的代码维护。
   至于您的收入问题，可以建议用户捐赠或者收费提供私有云，的导出和发布解决方案的。
   用户越多，您的软件才会发展的更好。
 祝更好
