### ISSUE TITLE
vip升级后没重启客户端，则没更新状态，也没找到更新按钮

### ISSUE THREAD

**Issue by Soidea** [zhaopengme/gitnote#124]
vip升级后没重启客户端，则没更新状态，也没找到更新按钮

win客户端，用户中心里面还是free

**Comment by zhaopengme** [comment]
来来直接联系我,微信  qq 都行. 或者告诉我你的邮箱,我看看

**Comment by Timehsw** [comment]
> vip升级后没重启客户端，则没更新状态，也没找到更新按钮
> 
> win客户端，用户中心里面还是free

@Soidea 退出登录,再重新登录即可显示VIP了

**Comment by zhaopengme** [comment]
ok
