### ISSUE TITLE
Cannot shut down properly

### ISSUE THREAD

**Issue by TerenceLiu98** [zhaopengme/gitnote#13]
System: macOS 10.14.2
App Version: V3.0.0 

Click  the "Yes" to close the button, it cannot close normally, but click "no" to exit.

**Comment by zhaopengme** [comment]
The next version will be fixed. thanks

**Comment by TerenceLiu98** [comment]
> The next version will be fixed. thanks

my pleasure.

**Comment by zhaopengme** [comment]
fixed 3.0.1.
