### ISSUE TITLE
新增手动提交文章的功能

### ISSUE THREAD

**Issue by Timehsw** [zhaopengme/gitnote#130]
1. 现在最大每3分钟一次自动提交,导致GitHub上的提交里面太多无用记录.这也不太好.建议给一个手动提交的功能,并且能输入提交更改信息. 这样GitHub的提交历史也就更好看了.
2. GitHub图床还是自动提交,但是有一个问题,当我发现这个图片不合适的时候,在文章中删除了这个图片,但是图床里面应该没有同步删除对吧,那么可以同步删除吗?

**Comment by zhaopengme** [comment]
1. todo 中增加这个需求了
2. 还不行,就算删除了,其实图床里面还是有这个图片的历史记录的.
