### ISSUE TITLE
centos shell不能执行 一定要GTK方式？

### ISSUE THREAD

**Issue by a123** [zhaopengme/gitnote#14]
[root@VM_0_16_centos home]# ./GitNote_setup_3.0.0.AppImage 
zenity, kdialog, Xdialog missing. Skipping /tmp/.mount_GitNotOcFszi/AppRun.

(gitnote:13633): Gtk-WARNING **: 12:18:39.430: cannot open display:

**Comment by zhaopengme** [comment]
我是 ubuntu 上面测试,我装个centos 测试下.

**Comment by zhaopengme** [comment]
![image](https://user-images.githubusercontent.com/1415418/52173109-0d2c8d00-27b8-11e9-8d70-e2493e2a0ac1.png)
你需要设置下权限

**Comment by zhaopengme** [comment]
centos 下面使用 GitNote
https://zhaopeng.me/index.php/archives/1559.html
