### ISSUE TITLE
建议增加选择文件时默认为单栏预览模式

### ISSUE THREAD

**Issue by MarvinLong** [zhaopengme/gitnote#145]
目前选择一个md文件后默认为双栏模型，有的时候需要查看很多以前的笔记，对于记录笔记多的感觉不是很方便。还要手动选择单栏然后在选择预览模式。

对于我的使用来说我更多的会去查看文件，而不是去编辑，当我编辑文件时，我打开一个文件会让他一直处于打开状态，然后陆陆续续的可能要写很久。所以我手动去调整 单栏 -> 双栏是可以接受的。

建议增加默认模式为 单栏 预览的情况， 谢谢！

**Comment by atomsyoung** [comment]
同意

**Comment by zhaopengme** [comment]
todo 增加设置
