### ISSUE TITLE
建议给新建日记增加MARKDOWN模式

### ISSUE THREAD

**Issue by kangseung** [zhaopengme/gitnote#148]
**建议给新建日记增加MARKDOWN模式**
**HTML模式格式排版打开会乱**

**Comment by kangseung** [comment]
另外想问一下怎么把图片插入笔记 保存在git上? 现在好像只有本地的图片

**Comment by zhaopengme** [comment]
日记模式已经增加了,  有图床插件.
https://www.gitnoteapp.com/zh/extensions/
