### ISSUE TITLE
【BUG】macos 下，软件界面按下 Cmd+Q，会出现提示，点击确认依然会继续弹出提示。

### ISSUE THREAD

**Issue by ferocknew** [zhaopengme/gitnote#15]
【BUG】macos 下，软件界面按下 Cmd+Q，会出现提示，点击确认依然会继续弹出提示。

**Comment by ferocknew** [comment]
![image](https://user-images.githubusercontent.com/2178683/52104730-e854e000-2626-11e9-861a-71cf4935d633.png)

**Comment by ferocknew** [comment]
按 No 会退出，按 Yes 会反复弹出 alert

**Comment by zhaopengme** [comment]
加我 qq 523419490 赵鹏

**Comment by ferocknew** [comment]
这么快就close 了？修复了？
