### ISSUE TITLE
无法查看分享的文件，点击查看没有反应

### ISSUE THREAD

**Issue by GooZy** [zhaopengme/gitnote#16]
System: macOS 10.14
App Version: V3.0.0

无法查看分享的文件，点击查看没有反应
![qq20190201-135020](https://user-images.githubusercontent.com/12698567/52105153-885f3900-2628-11e9-8ebb-7cad8c064076.png)

**Comment by zhaopengme** [comment]
bug 了.

**Comment by zhaopengme** [comment]
3.0.1 fixed 了
