### ISSUE TITLE
本地保存以后，无法同步到github上

### ISSUE THREAD

**Issue by wk8910** [zhaopengme/gitnote#166]
前几天一直正常，最近出了问题
在本地保存以后，github仓库中没有同步
不知道可能是什么问题？

**Comment by zhaopengme** [comment]
看看新手视频,如果还有问题 加我 qq 523419490 验证 赵鹏,我远程你.

**Comment by wk8910** [comment]
> 看看新手视频,如果还有问题 加我 qq 523419490 验证 赵鹏,我远程你.

找到原因了。
我在用两个电脑，第一个电脑上直接打开的github上的responsibility，在本地保存到一个网盘里面，保存后可以同步到github。在另外一个新电脑里面则是直接打开网盘同步过来的project，因此在这个新电脑打开的时候，并不会同步到github上。

**Comment by zhaopengme** [comment]
ok,请 close了吧
