### ISSUE TITLE
3.0.4版使用时发现的问题

### ISSUE THREAD

**Issue by yehbww** [zhaopengme/gitnote#171]
- 3.0.4版本升级后还算使用正常，但今天打开后注意到界面左下角的同步图标区域只剩下一个表示同步的圆圈图标还在，其他表示文件修改的信息MODIFIED和其他信息都消失了。人工点击圆圈也没有反应。程序也未按设置的时间进行自动同步。

- 设置中将日记格式定为MD后，保存退出。再次进入设置发现日记格式选择为空，但编辑器的设置显示正常。

- 以上问题，PORTABLE和SETUP版都试过了，均如此。

请核查。

**Comment by yehbww** [comment]
- 补充一下，昨天用MCT工具修复过系统。

**Comment by pwwcpp** [comment]
markdown笔记下的表格使用预览不对

**Comment by zhaopengme** [comment]
下载好了,如果还有问题,直接联系我.

**Comment by pwwcpp** [comment]
ok

zhaopeng <notifications@github.com> 于2019年2月28日周四 下午7:40写道：

**Comment by yehbww** [comment]
问题已解决。备份并清空本地文件夹，重新将远程仓库CLONE过来，然后用原来本地的文件夹覆盖掉CLONE来的仓库中的内容。现在恢复正常。

**Comment by zhaopengme** [comment]
ok.问题搞定就 close 吧
