### ISSUE TITLE
关键字搜索

### ISSUE THREAD

**Issue by CatCccC** [zhaopengme/gitnote#182]
1. 关键字搜索时 标题以及内容希望能够标注出来 ,在同一个文本中快速跳转到下一个关键字

1. 修改字体笔记本上(划重点,别的我都能克服一下

1. markDown 代码片段语法高亮

**Comment by wk8910** [comment]
第一点很赞同，现在的搜索不是很方便

**Comment by zhaopengme** [comment]
V4改进
提醒: 开始V4版本开发,V3不会有大的改动了.最近更新很慢.抱歉.

**Comment by chengzyzy** [comment]
收到,下一个版本预计何时发布 ?

zhaopeng <notifications@github.com> 于2019年3月19日周二 下午2:04写道：

**Comment by zhaopengme** [comment]
V4刚刚开始.得一段时间了.

**Comment by mackyliu** [comment]
现在有搜索吗？我怎么测试搜索没任何作用呢
