### ISSUE TITLE
官网版本非最新

### ISSUE THREAD

**Issue by singlepig** [zhaopengme/gitnote#186]
你好：
我发现gitnoteapp.com网站上下载的版本是3.0.3，下载安装完后打开就提示有新版本，github的release版本最新是3.0.4。
建议下载入口统一一下，或者版本更新后及时更新所有下载入口的链接。

此外，升级提示的弹出框似乎有些格式问题，序号都是1。弹出框加上个标题会更好一些。

![](https://i.loli.net/2019/03/05/5c7e80086776c.png
)

**Comment by zhaopengme** [comment]
https://zhaopeng.me/oneindex/?/gitnote/  已经更新了,这里下载国内速度快.
