### ISSUE TITLE
openSUSE Leap 15.0上无法启动应用

### ISSUE THREAD

**Issue by mengzyou** [zhaopengme/gitnote#187]
**Describe the bug**
在openSUSE Leap 5.0 （Linux）上，使用AppImage无法打开应用。

**To Reproduce**
1. 下载最新版本（3.0.4）的AppImage
2. 在终端（kconsole）中直接执行
3. 等待，一直没有界面弹出

**Screenshots**
![image](https://user-images.githubusercontent.com/360603/53850439-35e1b580-3ff6-11e9-99aa-2e6565b2b358.png)

**Desktop (please complete the following information):**
 - OS: openSUSE Leap 15.0

![image](https://user-images.githubusercontent.com/360603/53850462-53af1a80-3ff6-11e9-9481-099f9665383d.png)

**Comment by zhaopengme** [comment]
加我 qq 523419490 验证 赵鹏,我重新给你一个版本.

**Comment by mengzyou** [comment]
## 解决方案

```
sudo ln -s /usr/lib64/libcurl.so.4 /usr/lib/64/libcurl-gnutls.so.4
```

然后还要将`libopenssl1_0_0`包的版本降低到`1.0.1`。  


感谢 @zhaopengme 的亲历支持！

**Comment by XiongLin211** [comment]
我的manjaro 打开gitnote 一直在 加载画面，无论等多久都不行
