### ISSUE TITLE
markdown笔记不支持todo

### ISSUE THREAD

**Issue by cangfengzhs** [zhaopengme/gitnote#19]
![image](https://user-images.githubusercontent.com/22708345/52110168-c36a6800-263a-11e9-9d68-47e156c3ebc6.png)
上面这些在todo里没有
![image](https://user-images.githubusercontent.com/22708345/52110198-dda44600-263a-11e9-9741-cbe214c53eef.png)

**Comment by zhaopengme** [comment]
md开发计划中
