### ISSUE TITLE
安装弹出UAC，希望能避免触发，或者发布绿色版

### ISSUE THREAD

**Issue by woodwm** [zhaopengme/gitnote#194]
你好，单位电脑没有管理员权限，无法安装windows版的 `Gitnote`，希望能避免触发UAC，或者发布绿色版。

**Comment by zhaopengme** [comment]
好咧,稍等一下,我加个绿色版.

**Comment by woodwm** [comment]
谢谢及时回复。

**Comment by zhaopengme** [comment]
https://zhaopeng.me/oneindex/?/gitnote/  github 也上传了,这里下载应该能快点.

**Comment by woodwm** [comment]
跟我直接用7-Zip解压出来的差不多，哈哈。
