### ISSUE TITLE
need portable version

### ISSUE THREAD

**Issue by branchus** [zhaopengme/gitnote#2]
Cannot install new software on company computers plus I like the put it on usb and use it everywhere
Please consider

**Comment by walklty** [comment]
I just install the software in another PC and copy the folder into company computer. It works.

**Comment by branchus** [comment]
> I just install the software in another PC and copy the folder into company computer. It works.

yep, a lot of app probably can do portable like this, what i mean portable is first to have a portable zip archive, second all the settings goes to the application folder and don't access registry.

Thanks

**Comment by zhaopengme** [comment]
ok. I have added portable version, you can download it here.
https://github.com/zhaopengme/gitnote/releases
