### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by Royyu1215** [zhaopengme/gitnote#22]
1. 文档的示范用例不是很清晰,作为一个产品用例应清晰明了并且能按部就班完成所需功能
2.可能是我太笨,并没有找到创建待办事项的按钮
3.感谢做出这个笔记软件.

**Comment by zhaopengme** [comment]
![todo](https://user-images.githubusercontent.com/1415418/52118907-8ca04c00-2652-11e9-9f0a-7276d1986b57.gif)
创建 todo.
文档我更新下.谢谢!
