### ISSUE TITLE
能否像typora一样插入图片的时候直接复制到文件夹

### ISSUE THREAD

**Issue by ComCtrl** [zhaopengme/gitnote#246]
hi，之前用的都是 typora，感觉最方便的功能就是截图后直接贴到 markdown文件中（不用先保存截图到本地，然后再复制路径到markdown文件中）然后图片会自动插入到指定的文件夹，能否增加一下这个功能，插入完成后可以直接和笔记一起进行同步，不使用图床，不知道我说清楚没有。
![2](https://user-images.githubusercontent.com/3320501/55218572-715e5100-523d-11e9-8215-0d47a9ebade5.gif)

**Comment by ComCtrl** [comment]
最近的 3.1.0 已经实现类似功能

**Comment by S-unny** [comment]
可以么？为什么我的最新版不行？
