### ISSUE TITLE
deepin linux 下 插件无法安装

### ISSUE THREAD

**Issue by d100972** [zhaopengme/gitnote#28]
deepin linux 下 基于debian  
所有插件无法安装  
错误提示只是红叉，没有文字

**Comment by d100972** [comment]
已解决，感谢。

**Comment by LoongLiWang** [comment]
这个时怎么解决的呢？

**Comment by d100972** [comment]
最新版可以了，已经修复



小巧玲珑藏壮志 佳妙才华做栋梁
在 LoongLiWang <notifications@github.com>，2019年2月7日 20:41写道：

这个时怎么解决的呢？
