### ISSUE TITLE
无法登陆：request failed with status code：404

### ISSUE THREAD

**Issue by flyuh** [zhaopengme/gitnote#3]
![_20190201085225](https://user-images.githubusercontent.com/25998723/52095638-bb8cd280-25fe-11e9-8b71-50301db4c7db.jpg)

**Comment by zhaopengme** [comment]
![image](https://user-images.githubusercontent.com/1415418/52098688-f7c63000-260a-11e9-94b1-37b472be8205.png)
这个要是自己的 git 仓库地址的.不会主动获取你的 github 仓库列表
