### ISSUE TITLE
开源

### ISSUE THREAD

**Issue by vivaxy** [zhaopengme/gitnote#35]
通过社区共建，提高支持新特性的速度

**Comment by hustxujinkang** [comment]
笔记软件不开源有点不敢用，真怕哪天就停止支持了

**Comment by zhaopengme** [comment]
我自己使用的，会一直维护下去的。
未来会考虑开源的

**Comment by godvmxi** [comment]
> 我自己使用的，会一直维护下去的。
> 未来会考虑开源的

其实可以考虑开源的，然后我们大家一起做，然后可以在一起企业级的需求上做定制收费的。。。比如时文档美化，私有化，导出等，效果挺好的，
做好了，别人会给你投资的

**Comment by godvmxi** [comment]
> 我自己使用的，会一直维护下去的。
> 未来会考虑开源的

我看你网站挂了，其实建议用git io做一个就行了，永久免费，国内可以考虑用cdn加速一下就行了，费用很低的
