### ISSUE TITLE
所见即所得

### ISSUE THREAD

**Issue by woniuxia** [zhaopengme/gitnote#36]
请问后续会考虑支持所见即所得吗？

**Comment by zhaopengme** [comment]
你指的是？

**Comment by ShangWei97** [comment]
就像typora那种，输入完就是渲染完的样子

**Comment by zhaopengme** [comment]
ok,明白了.现在支持左右显示.你这个需求我作为预留吧.按照实际使用,我经常需要用 md 的源码格式的.
![image](https://user-images.githubusercontent.com/1415418/52160856-9fb92780-26f7-11e9-952a-86e42e6f65ed.png)
