### ISSUE TITLE
[bug]新建子目录后没有及时同步

### ISSUE THREAD

**Issue by GooZy** [zhaopengme/gitnote#37]
System: macOS 10.14
App Version: V3.0.1

新建子目录后没有及时同步

![9e42e5d0dd958e4b848eba7b8043ca6f](https://user-images.githubusercontent.com/12698567/52159313-6a074500-26dd-11e9-8dcc-4561a6442732.jpg)

**Comment by zhaopengme** [comment]
![image](https://user-images.githubusercontent.com/1415418/52160894-48678700-26f8-11e9-91ff-48406868904c.png)
这里有个刷新,可以先用.以后加监控.
