### ISSUE TITLE
历史界面空白

### ISSUE THREAD

**Issue by grayson-kuo** [zhaopengme/gitnote#41]
![image](https://user-images.githubusercontent.com/17007382/52162035-f844f080-2708-11e9-8407-11a0049e82ac.png)
可以同步到GitHub，但是不论在win还是os x下面历史记录都是空白，是哪里设置不对吗。

**Comment by zhaopengme** [comment]
bug 了

**Comment by zhaopengme** [comment]
fixed 3.0.3
