### ISSUE TITLE
manjaro 

### ISSUE THREAD

**Issue by CatCccC** [zhaopengme/gitnote#42]
manjaro 启动 一直在加载页 
![screenshot_20190202_182032](https://user-images.githubusercontent.com/30223515/52163043-3cd78880-2717-11e9-958b-46277324ce30.png)

**Comment by zhaopengme** [comment]
怎么操作的呢？
是添加本地git文件夹吗？

**Comment by jimersylee** [comment]
同样的情况,manjaro系统,第一次运行

$ ./GitNote_setup_3.0.1.AppImage                                                                                                                                 [22:33:05]
(node:31274) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: socket hang up
(node:31274) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

程序界面一直卡住
本地node版本 v10.15.0
 $ screenfetch                                                                                                                                                    [22:36:56]

 ██████████████████  ████████     jimersylee@laptop
 ██████████████████  ████████     OS: Manjaro 18.0.2 Illyria
 ██████████████████  ████████     Kernel: x86_64 Linux 4.19.16-1-MANJARO
 ██████████████████  ████████     Uptime: 6d 7h 2m
 ████████            ████████                    Packages: 1286
 ████████  ████████  ████████     Shell: zsh 5.6.2
 ████████  ████████  ████████     Resolution: 1920x1080
 ████████  ████████  ████████     DE: GNOME 
 ████████  ████████  ████████     WM: GNOME Shell
 ████████  ████████  ████████     WM Theme: Sierra-light
 ████████  ████████  ████████     GTK Theme: Sierra-compact-light [GTK2/3]
 ████████  ████████  ████████     Icon Theme: Papirus-Maia
 ████████  ████████  ████████     Font: Noto Sans 11
 ████████  ████████  ████████     CPU: Intel Core i7-8550U @ 8x 4GHz [36.0°C]
                                                                       GPU: Unknown
                                                                       RAM: 6734MiB / 15923MiB

**Comment by codelalala** [comment]
同样是Manjaro，KDE.
第一次运行提示：Failed to load module "appmenu-gtk-module"
安装之后提示：Segmentation fault (core dumped)

**Comment by zhaopengme** [comment]
https://zhaopeng.me/index.php/archives/1559.html
试试这样按可以吗?
我装个manjaro,试试

**Comment by zhaopengme** [comment]
@CatCccC @jimersylee @codelalala 你们谁可以加一下我的QQ 523419490 验证 赵鹏. 我对manjaro不太熟悉,有些问题需要你们帮忙一起看看.

**Comment by zhaopengme** [comment]
@codelalala 还在线啊  imzhpe@qq.com 可以啊

**Comment by zhaopengme** [comment]
@codelalala 你收到我邮件了吗

**Comment by zhaopengme** [comment]
@CatCccC @jimersylee @codelalala 搞定了. 看看这个.
https://zhaopeng.me/index.php/archives/manjaro-use-gitnote.html

**Comment by CatCccC** [comment]
@zhaopengme thanks

**Comment by jimersylee** [comment]
@CatCccC 你解决了吗?我还是卡在那~

**Comment by CatCccC** [comment]
安装步骤操作以后 已经能够正常使用了

Jimersy Lee <notifications@github.com> 于2019年2月19日周二 上午10:03写道：
