### ISSUE TITLE
[feature]允许用户调整主界面样式

### ISSUE THREAD

**Issue by yiding-he** [zhaopengme/gitnote#44]
希望能允许用户指定某个 CSS 文件，用来调整主界面（比如创建一个更紧凑的界面样式）。同时也需要开放主界面的开发者模式，并且添加一个重新加载应用的功能（类似 VSCode），方便用户一边调整 CSS 一边预览。

**Comment by zhaopengme** [comment]
目前的重心在稳定版本上面.主题调整等版本稳定后后再做.
