### ISSUE TITLE
待办功能不能使用

### ISSUE THREAD

**Issue by feibuguocanghai** [zhaopengme/gitnote#5]
无法新建待办事项

**Comment by zhaopengme** [comment]
![todo](https://user-images.githubusercontent.com/1415418/52098653-d7967100-260a-11e9-81fb-f6f67e6c4efe.gif)
你试试这样可以用吗

**Comment by andyhuai** [comment]
markdown文件就不行，很多标签都不识别，[]无法识别，有序和无序等识别不了，解析模板还是有问题的

**Comment by zhaopengme** [comment]
markdown 的还么有做.这个是 todo 中需要做的.
