### ISSUE TITLE
无法克隆github远程仓库

### ISSUE THREAD

**Issue by maboloshi** [zhaopengme/gitnote#50]
提示：credentials callback returned an invalid cred type

不知道是不是跟我开启二步验证有关

**Comment by zhaopengme** [comment]
应该是的,尽快我支持 token 方式,应该就不会了.

**Comment by zhaopengme** [comment]
你可以先关闭,clone 下来后,再开启.

**Comment by maboloshi** [comment]
关闭二步验证 可以克隆了

**Comment by zhaopengme** [comment]
ok.
