### ISSUE TITLE
支持[TOC]

### ISSUE THREAD

**Issue by WhenMelancholy** [zhaopengme/gitnote#52]
可否支持`[TOC]`标签，实现这种效果？
![image](https://user-images.githubusercontent.com/21274779/52192519-70382580-2885-11e9-8399-5525ad972047.png)

**Comment by zhaopengme** [comment]
是md吧，可以的，我先加入todo

**Comment by zhaopengme** [comment]
@BalanceUhen markdown 支持 toc 标签的
