### ISSUE TITLE
Todo样式有点诡异

### ISSUE THREAD

**Issue by n37r06u3** [zhaopengme/gitnote#55]
Todo渲染样式在windows 10下  有点诡异

**Comment by zhaopengme** [comment]
我测试下.

**Comment by 3364** [comment]
mac里todo的情况也很轻快，我是在富文本输入框里直接点击todo的按钮。结果出现了一条横线。我用鼠标点击才知道这个是todo liste

**Comment by zhaopengme** [comment]
fixed 3.0.3
