### ISSUE TITLE
windows版本 标题栏有点小

### ISSUE THREAD

**Issue by n37r06u3** [zhaopengme/gitnote#57]
windows版本 标题栏有点小，关闭按钮等与下面的微信 qq 微博等图标重叠，影响美观

**Comment by yiding-he** [comment]
![explorer_agygcehefa](https://user-images.githubusercontent.com/900606/52280805-a796f700-2997-11e9-9733-a4af75b0a95a.png)

附议

**Comment by zhaopengme** [comment]
ok todo 几下了

**Comment by zhaopengme** [comment]
fixed 3.0.3
