### ISSUE TITLE
不能新建文件夹

### ISSUE THREAD

**Issue by feibuguocanghai** [zhaopengme/gitnote#6]
无论输入中文或者英文都提示包含特殊字符。
windows 7系统

**Comment by gulucn** [comment]
win10 home下也有同样的出错

**Comment by zhaopengme** [comment]
@feibuguocanghai @gulucn 我装个 win7 试试先.

**Comment by Eternaldeath** [comment]
同上 win10 无法创建文件夹（子目录），中英文都是报错包含特殊字符

**Comment by zhaopengme** [comment]
请重新下载,刚刚解决了这个问题了.
