### ISSUE TITLE
win客户端3.0.2 TODO复选框显示不正常

### ISSUE THREAD

**Issue by grayson-kuo** [zhaopengme/gitnote#62]
如图，未被勾选的时候显示不正常，勾选的时候没有问题
![snipaste_2019-02-06_10-46-30](https://user-images.githubusercontent.com/17007382/52317830-a6e47c00-29fc-11e9-8c29-2c365522c199.png)

**Comment by zhaopengme** [comment]
ok  我修复下

**Comment by 3364** [comment]
MAC客户端也是同样的问题
<img width="186" alt="capture d ecran 2019-02-08 a 12 23 42" src="https://user-images.githubusercontent.com/24705408/52476073-cbc42500-2b9d-11e9-99fb-eeda4fd0fbcb.png">

**Comment by zhaopengme** [comment]
fixed 3.0.3
