### ISSUE TITLE
编辑器插件化等建议

### ISSUE THREAD

**Issue by GuyFawkesNight** [zhaopengme/gitnote#84]
首先非常感谢作者提供开源的笔记软件。

我现在主要是以为知笔记作为主力的笔记软件，所以难免特性趋向为知笔记，作者可以酌情选择修改和实现：
1.  当前gitnote中的编辑模式只有两种，而为知笔记的实现方式是将编辑器作为可选项，将编辑器插件化，不知道对于你的软件是否具备实现条件，毕竟优秀的编辑器很多，也可以避免重复开发。

2. 对于笔记的重度用户来说，一般都有自己长期使用的笔记软件，如果需要平台迁移势必需要一个方便的接口，该方案是否在你的未来规划之内呢？

以上建议仅供参考。

**Comment by zhaopengme** [comment]
谢谢支持
1. 编辑器插件化,有计划,可以支持多个编辑器,应该需要一段时间,才能完成
2. 平台迁移采用插件方式提供,计划开发中了.
再次感谢.
