### ISSUE TITLE
将markdown文档使用reveal插件生成后，使用网页浏览没有滚动条

### ISSUE THREAD

**Issue by xinxuwang** [zhaopengme/gitnote#85]
你好，非常喜欢这个项目。

目前发现markdown在用reveal转化后，放到nginx中发现没有滚动条，导致文档现实不完全。

**Comment by zhaopengme** [comment]
谢谢.
在PPT每页的设计原则上,是不能出现滚动条的,每页就显示屏幕大小的内容的,如果超过,就再增加一页.
![image](https://user-images.githubusercontent.com/1415418/52609266-a2fea100-2eb7-11e9-90f6-3dcd596854e1.png)
如果你需要滚动条,可以这样修改.
修改 section 的 css 如下:
`<section class="scrollable">`

```
.scrollable {
    bottom: 0px;
    overflow-y: auto  !important;
    overflow-x: hidden !important;
}

```
