### ISSUE TITLE
有两个问题请帮忙解答

### ISSUE THREAD

**Issue by lb8023lyy** [zhaopengme/gitnote#86]
1.为什么每次软件都会新建一个favourite文件夹，删除也没有
2.笔记中链接打开后窗口怎么关闭（只能任务栏关闭），能否不使用内置浏览器，调用外部浏览器打开链接

**Comment by zhaopengme** [comment]
1. favourite 是web 收藏使用的功能,同步会就会自动进入这个目录.我加入优化,么有内容就不做创建了
2. 优化需求中
